-- @block insert data into Category
INSERT INTO Category (categoryName, categoryDescription) VALUES
('Electronics', 'Latest and greatest electronics'),
('Furniture', 'Quality and affordable furniture'),
('Apparel', 'Trendy and fashionable clothing'),
('Literature', 'Wide range of books'),
('Athletics', 'Sports equipment for all ages'),
('MusicGear', 'Music instruments and accessories'),
('ChildrensToys', 'Fun toys for kids'),
('Cookware', 'Essential kitchen appliances'),
('Horticulture', 'Gardening tools and plants'),
('Artwork', 'Beautiful art pieces'),
('Vehicles', 'Cars, bikes and more'),
('Jewelry', 'Elegant jewelry pieces'),
('Hardware', 'Handy tools for all your needs'),
('PetSupplies', 'Pet supplies and accessories'),
('Cosmetics', 'Beauty products for self-care'),
('Gaming', 'Board and video games'),
('OfficeSupplies', 'Office supplies and equipment'),
('Antiquities', 'Antique items with a history'),
('EventTickets', 'Tickets for concerts, sports and more'),
('CraftSupplies', 'Craft supplies for DIY projects'),
('HomeAppliances', 'Home appliances for everyday use'),
('ExerciseEquipment', 'Fitness equipment for home workouts'),
('OutdoorGear', 'Outdoor gear for camping and adventures'),
('InfantCare', 'Baby essentials for new parents'),
('Collectibles', 'Unique collectibles'),
('ComputerHardware', 'Computer parts and accessories'),
('Photography', 'Cameras for photography enthusiasts'),
('MobileDevices', 'Phones from top brands'),
('Timepieces', 'Luxury watches'),
('Instruments', 'Musical instruments for all levels');
