-- @block insert data into Location
insert into Location (locationID, city, ZIPCode) values (1, 'Dagui', 'R0H 3D3');
insert into Location (locationID, city, ZIPCode) values (2, 'Bobolice', 'Z5H 1Y9');
insert into Location (locationID, city, ZIPCode) values (3, 'Santa Maria', 'P2G 1T1');
insert into Location (locationID, city, ZIPCode) values (4, 'Río Sereno', 'S4W 0U9');
insert into Location (locationID, city, ZIPCode) values (5, 'Orsk', 'O3B 7T9');
insert into Location (locationID, city, ZIPCode) values (6, 'Ragana', 'D3U 3J4');
insert into Location (locationID, city, ZIPCode) values (7, 'Salto', 'T2X 4K5');
insert into Location (locationID, city, ZIPCode) values (8, 'Corzuela', 'X7O 5M0');
insert into Location (locationID, city, ZIPCode) values (9, 'Port-de-Paix', 'G5Y 6O3');
insert into Location (locationID, city, ZIPCode) values (10, 'Fort Worth', 'Z2U 8O9');
insert into Location (locationID, city, ZIPCode) values (11, 'Maple Ridge', 'Q0X 8B9');
insert into Location (locationID, city, ZIPCode) values (12, 'Uk', 'T6Q 5E4');
insert into Location (locationID, city, ZIPCode) values (13, 'Nechanice', 'V2A 4T0');
insert into Location (locationID, city, ZIPCode) values (14, 'Göteborg', 'R8P 3D4');
insert into Location (locationID, city, ZIPCode) values (15, 'Florida', 'N8Y 4C8');
insert into Location (locationID, city, ZIPCode) values (16, 'Ban Dung', 'H8M 0W3');
insert into Location (locationID, city, ZIPCode) values (17, 'Sumberrejo', 'U8S 7M4');
insert into Location (locationID, city, ZIPCode) values (18, 'Villefranche-sur-Saône', 'T9M 4H5');
insert into Location (locationID, city, ZIPCode) values (19, 'Tangban', 'K2F 2Y8');
insert into Location (locationID, city, ZIPCode) values (20, 'Khon Buri', 'E8X 1L9');
insert into Location (locationID, city, ZIPCode) values (21, 'Laocheng', 'S0T 6V2');
insert into Location (locationID, city, ZIPCode) values (22, 'Kalino', 'U9S 7D9');
insert into Location (locationID, city, ZIPCode) values (23, 'Cẩm Phả Mines', 'Y5W 8K9');
insert into Location (locationID, city, ZIPCode) values (24, 'Fontana', 'E1J 5H7');
insert into Location (locationID, city, ZIPCode) values (25, 'Varāmīn', 'U7Q 3T5');
insert into Location (locationID, city, ZIPCode) values (26, 'Licupis', 'Q3B 0B5');
insert into Location (locationID, city, ZIPCode) values (27, 'Belopa', 'M8B 3V6');
insert into Location (locationID, city, ZIPCode) values (28, 'Hengtang', 'C8R 7W3');
insert into Location (locationID, city, ZIPCode) values (29, 'Jiangwan', 'A8C 9F5');
insert into Location (locationID, city, ZIPCode) values (30, 'Andongsari', 'M1A 2E8');
insert into Location (locationID, city, ZIPCode) values (31, 'Qo’ng’irot Shahri', 'A7B 9M2');
insert into Location (locationID, city, ZIPCode) values (32, 'Xianlin', 'Q4J 6G7');
insert into Location (locationID, city, ZIPCode) values (33, 'Cortinhas', 'G4J 0Y7');
insert into Location (locationID, city, ZIPCode) values (34, 'Kentville', 'N8K 7W3');
insert into Location (locationID, city, ZIPCode) values (35, 'Dalu', 'G5P 4A8');
insert into Location (locationID, city, ZIPCode) values (36, 'Włoszczowa', 'Z3D 9U3');
insert into Location (locationID, city, ZIPCode) values (37, 'Černošice', 'I5Y 5D4');
insert into Location (locationID, city, ZIPCode) values (38, 'Puunage', 'M7Q 9W1');
insert into Location (locationID, city, ZIPCode) values (39, 'Su’ao', 'V5Q 7Y9');
insert into Location (locationID, city, ZIPCode) values (40, 'Rafaela', 'G1U 1U4');
insert into Location (locationID, city, ZIPCode) values (41, 'Saumur', 'M6N 2D5');
insert into Location (locationID, city, ZIPCode) values (42, 'Burgos', 'R8E 8X7');
insert into Location (locationID, city, ZIPCode) values (43, 'La Mohammedia', 'C9G 6J1');
insert into Location (locationID, city, ZIPCode) values (44, 'Lomé', 'G2I 6Y0');
insert into Location (locationID, city, ZIPCode) values (45, 'Ocoruro', 'H1W 0Y5');
insert into Location (locationID, city, ZIPCode) values (46, 'Duogongma', 'W7Z 8X3');
insert into Location (locationID, city, ZIPCode) values (47, 'Gaspar Hernández', 'T2E 6X2');
insert into Location (locationID, city, ZIPCode) values (48, 'Cibojong', 'N3U 3K5');
insert into Location (locationID, city, ZIPCode) values (49, 'Finspång', 'X7M 7O8');
insert into Location (locationID, city, ZIPCode) values (50, 'Ouésso', 'S1G 5C4');
insert into Location (locationID, city, ZIPCode) values (51, 'Taroudant', 'J0Q 3G9');
insert into Location (locationID, city, ZIPCode) values (52, 'Sabugal', 'R5T 5J9');
insert into Location (locationID, city, ZIPCode) values (53, 'Makilala', 'S3A 3P1');
insert into Location (locationID, city, ZIPCode) values (54, 'Fatukanutu', 'M5O 7H6');
insert into Location (locationID, city, ZIPCode) values (55, 'Stockholm', 'B8Y 9P8');
insert into Location (locationID, city, ZIPCode) values (56, 'Quwa', 'J3Y 8N3');
insert into Location (locationID, city, ZIPCode) values (57, 'Maramag', 'C8Y 3M7');
insert into Location (locationID, city, ZIPCode) values (58, 'Changhua', 'U9V 9S4');
insert into Location (locationID, city, ZIPCode) values (59, 'Zhuangbian', 'F1H 0B7');
insert into Location (locationID, city, ZIPCode) values (60, 'Zahedan', 'U6Z 2D6');
insert into Location (locationID, city, ZIPCode) values (61, 'La Gloria', 'P0I 7R1');
insert into Location (locationID, city, ZIPCode) values (62, 'Krajan Curahcotok', 'A1I 7L7');
insert into Location (locationID, city, ZIPCode) values (63, 'Saint-Denis', 'V6Y 4F1');
insert into Location (locationID, city, ZIPCode) values (64, 'Benevides', 'F1M 1W2');
insert into Location (locationID, city, ZIPCode) values (65, 'Wright', 'I3N 1I3');
insert into Location (locationID, city, ZIPCode) values (66, 'Matanzas', 'F3U 8F8');
insert into Location (locationID, city, ZIPCode) values (67, 'Rabāţ-e Sangī-ye Pā’īn', 'E1E 9E6');
insert into Location (locationID, city, ZIPCode) values (68, 'Grivenskaya', 'H3E 6U8');
insert into Location (locationID, city, ZIPCode) values (69, 'Kurmanayevka', 'I5I 7P7');
insert into Location (locationID, city, ZIPCode) values (70, 'Capacho Nuevo', 'V3E 5F6');
insert into Location (locationID, city, ZIPCode) values (71, 'Xiyuan', 'M2I 8K0');
insert into Location (locationID, city, ZIPCode) values (72, 'Pélla', 'T3Z 9M3');
insert into Location (locationID, city, ZIPCode) values (73, 'Huangfang', 'D7W 4M9');
insert into Location (locationID, city, ZIPCode) values (74, 'Tanrake Village', 'Z0A 6A2');
insert into Location (locationID, city, ZIPCode) values (75, 'Vroutek', 'L7H 7P3');
insert into Location (locationID, city, ZIPCode) values (76, 'Nerópolis', 'U6R 3Z6');
insert into Location (locationID, city, ZIPCode) values (77, 'Dolna Banjica', 'W8L 9O5');
insert into Location (locationID, city, ZIPCode) values (78, 'Muncar', 'M0I 7A7');
insert into Location (locationID, city, ZIPCode) values (79, 'Horodyshche', 'L9N 8E6');
insert into Location (locationID, city, ZIPCode) values (80, 'Odeleite', 'Y7N 1C0');
insert into Location (locationID, city, ZIPCode) values (81, 'Ouadda', 'V3C 8O6');
insert into Location (locationID, city, ZIPCode) values (82, 'Baiquan', 'W6G 3Q1');
insert into Location (locationID, city, ZIPCode) values (83, 'Zlatograd', 'K3Y 7T0');
insert into Location (locationID, city, ZIPCode) values (84, 'Bay-ang', 'U6L 0W3');
insert into Location (locationID, city, ZIPCode) values (85, 'Liudaogou', 'K4I 9K7');
insert into Location (locationID, city, ZIPCode) values (86, 'Bayanbaogede', 'P3P 8E9');
insert into Location (locationID, city, ZIPCode) values (87, 'Leština', 'H9R 7L8');
insert into Location (locationID, city, ZIPCode) values (88, 'Kiarajangkung', 'F3H 5X3');
insert into Location (locationID, city, ZIPCode) values (89, 'Guohe', 'B9P 9Q5');
insert into Location (locationID, city, ZIPCode) values (90, 'Bangassou', 'L9F 4R8');
insert into Location (locationID, city, ZIPCode) values (91, 'Sundsvall', 'K1V 6V3');
insert into Location (locationID, city, ZIPCode) values (92, 'Mashan', 'A5O 4N7');
insert into Location (locationID, city, ZIPCode) values (93, 'Sionogan', 'X1P 4I8');
insert into Location (locationID, city, ZIPCode) values (94, 'Xinxian', 'L8I 9H8');
insert into Location (locationID, city, ZIPCode) values (95, 'Pedro Santana', 'F8J 8N5');
insert into Location (locationID, city, ZIPCode) values (96, 'La Sierpe', 'H4X 0D6');
insert into Location (locationID, city, ZIPCode) values (97, 'Kujang-ŭp', 'I6J 3M2');
insert into Location (locationID, city, ZIPCode) values (98, 'Garça', 'Y7P 2F8');
insert into Location (locationID, city, ZIPCode) values (99, 'Tipolo', 'W8K 1D4');
insert into Location (locationID, city, ZIPCode) values (100, 'La Uvita', 'F2W 4T1');